### ISSUE TITLE
Parser can'd handle fancy YAML strings

### ISSUE THREAD

**Issue by JeanChristopheMorinPerso** [conda/conda-recipe-manager#116]
While doing some testing, I found an obscure case with this recipe:

<details><summary>Recipe</summary>

```yaml

# This file created by conda-build 3.18.5
# meta.yaml template originally from:
# /path/here, last modified Wed Jul  3 11:38:55 2019
# ------------------------------------------------
package:
    name: _anaconda_depends
    version: '2018.12'
build:
    ignore_run_exports:
        - '*'
    number: '0'
    string: py27_0
requirements:
    is_meta_pkg:
        - true
    run:
        - alabaster
        - anaconda-client
        - anaconda-project
        - asn1crypto
        - astroid
        - astropy
        - atomicwrites
        - attrs
        - babel
        - backports
        - backports.functools_lru_cache
        - backports.os
        - backports.shutil_get_terminal_size
        - backports_abc
        - beautifulsoup4
        - bitarray
        - bkcharts
        - blas
        - blaze
        - bleach
        - blosc
        - bokeh
        - boto
        - bottleneck
        - bzip2
        - ca-certificates
        - cairo
        - cdecimal
        - certifi
        - cffi
        - chardet
        - click
        - cloudpickle
        - clyent
        - colorama
        - configparser
        - contextlib2
        - cryptography
        - curl
        - cycler
        - cython
        - cytoolz
        - dask
        - dask-core
        - datashape
        - dbus
        - decorator
        - defusedxml
        - distributed
        - docutils
        - entrypoints
        - enum34
        - et_xmlfile
        - expat
        - fastcache
        - filelock
        - flask
        - flask-cors
        - fontconfig
        - freetype
        - fribidi
        - funcsigs
        - functools32
        - future
        - futures
        - get_terminal_size
        - gevent
        - glib
        - glob2
        - gmp
        - gmpy2
        - graphite2
        - greenlet
        - grin
        - gst-plugins-base
        - gstreamer
        - h5py
        - harfbuzz
        - hdf5
        - heapdict
        - html5lib
        - icu
        - idna
        - imageio
        - imagesize
        - importlib_metadata
        - intel-openmp
        - ipaddress
        - ipykernel
        - ipython
        - ipython_genutils
        - ipywidgets
        - isort
        - itsdangerous
        - jbig
        - jdcal
        - jedi
        - jinja2
        - jpeg
        - jsonschema
        - jupyter
        - jupyter_client
        - jupyter_console
        - jupyter_core
        - jupyterlab
        - jupyterlab_launcher
        - kiwisolver
        - krb5
        - lazy-object-proxy
        - libarchive
        - libcurl
        - libedit
        - libffi
        - libgcc-ng
        - libgfortran-ng
        - liblief
        - libpng
        - libsodium
        - libssh2
        - libstdcxx-ng
        - libtiff
        - libtool
        - libuuid
        - libxcb
        - libxml2
        - libxslt
        - linecache2
        - llvmlite
        - locket
        - lxml
        - lz4-c
        - lzo
        - markupsafe
        - matplotlib
        - mccabe
        - mistune
        - mkl
        - mkl-service
        - mkl_fft
        - mkl_random
        - more-itertools
        - mpc
        - mpfr
        - mpmath
        - msgpack-python
        - multipledispatch
        - nbconvert
        - nbformat
        - ncurses
        - networkx
        - nltk
        - nose
        - notebook
        - numba
        - numexpr
        - numpy
        - numpy-base
        - numpydoc
        - odo
        - olefile
        - openpyxl
        - openssl
        - packaging
        - pandas
        - pandoc
        - pandocfilters
        - pango
        - parso
        - partd
        - patchelf
        - path.py
        - pathlib2
        - patsy
        - pcre
        - pep8
        - pexpect
        - pickleshare
        - pillow
        - pip
        - pixman
        - pkginfo
        - pluggy
        - ply
        - prometheus_client
        - prompt_toolkit
        - psutil
        - ptyprocess
        - py
        - py-lief
        - pycairo
        - pycodestyle
        - pycosat
        - pycparser
        - pycrypto
        - pycurl
        - pyflakes
        - pygments
        - pylint
        - pyodbc
        - pyopenssl
        - pyparsing
        - pyqt
        - pysocks
        - pytables
        - pytest
        - python 2.7.*
        - python-dateutil
        - python-libarchive-c
        - pytz
        - pywavelets
        - pyyaml
        - pyzmq
        - qt
        - qtawesome
        - qtconsole
        - qtpy
        - readline
        - requests
        - rope
        - ruamel_yaml
        - scandir
        - scikit-image
        - scikit-learn
        - scipy
        - seaborn
        - send2trash
        - setuptools
        - simplegeneric
        - singledispatch
        - sip
        - six
        - snappy
        - snowballstemmer
        - sortedcollections
        - sortedcontainers
        - sphinx
        - sphinxcontrib
        - sphinxcontrib-websupport
        - spyder
        - spyder-kernels
        - sqlalchemy
        - sqlite
        - ssl_match_hostname
        - statsmodels
        - subprocess32
        - sympy
        - tblib
        - terminado
        - testpath
        - tk
        - toolz
        - tornado
        - tqdm
        - traceback2
        - traitlets
        - typing
        - unicodecsv
        - unittest2
        - unixodbc
        - urllib3
        - wcwidth
        - webencodings
        - werkzeug
        - wheel
        - widgetsnbextension
        - wrapt
        - wurlitzer
        - xlrd
        - xlsxwriter
        - xlwt
        - xz
        - yaml
        - zeromq
        - zict
        - zlib
        - zstd
about:
    description: 'Anaconda is a Python distribution which includes over 400
        Python packages for science, math, engineering, and data analysis.

        '
    dev_url: https://github.com/ContinuumIO/anaconda
    doc_url: https://docs.anaconda.com/anaconda
    home: https://www.anaconda.com/distribution
    license: BSD
    summary: Simplifies package management and deployment of Anaconda
extra:
    copy_test_source_files: true
    final: true
```
</details>

CRM is not able to parse that recipe.
