### ISSUE TITLE
Multi-line strings containing quotes breaks the parser

### ISSUE THREAD

**Issue by schuylermartin45** [conda/conda-recipe-manager#220]
Quotes in multi-line strings cause the parser to crash in a few different ways.

For example:

```yaml
about:                                                                          
  summary: fooo                                                                 
    'bar' bar         
```
Results in:
```
EXCEPTION: An exception occurred while parsing the recipe file
did not find expected <document start>
  in "<unicode string>", line 1, column 7
```

**Comment by schuylermartin45** [comment]
Looks like this is not limited to quotes, but also includes other special characters:
And
```yaml
about:                                                                          
  summary: |
    fooo (bar) bar       
```
Results in:
```
EXCEPTION: An exception occurred while parsing the recipe file
list index out of range
```
