### ISSUE TITLE
Refactor canonical sorting work found in the `RecipeParserConvert` class

### ISSUE THREAD

**Issue by schuylermartin45** [conda/conda-recipe-manager#234]
@ForgottenProgramme made an excellent call-out while we were talking off-line today.

The recipe bumper should _canonically_ sort recipe file keys when new keys are added.

For example, if `/build/number` is missing in the `/build` section, we'll add it:
```yaml
build:
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
```
But `RecipeParser::patch()` makes no guarantees/offers no control over the ordering of keys in the YAML structure.

We've run into this before with `crm convert`. There is an unofficial "canonical" sort-order that "most" recipes follow. This is likely an artifact of Grayskull's output or package builder preference. Some fields being out-of-order "just looks wrong".

So to combat this problem, we likely need to move some existing functionality of `RecipeParserConvert` out of the V0 --> V1 conversion work to a more broad location. When that is done, we should have a new public interface that allows the canonical sorting of all sections for any `RecipeParser` instance.
