### ISSUE TITLE
Error converting a recipe with a set `python_min` variable

### ISSUE THREAD

**Issue by hadim** [conda/conda-recipe-manager#307]
The bug was originally reported at https://github.com/hadim/feedrattler/issues/4.

When trying to convert https://github.com/conda-forge/pyhf-feedstock/blob/5f1ecaec210f588db912f57823a3d142a7c50da4/recipe/meta.yaml with `pixi exec conda-recipe-manager convert meta.yaml`, the command generates:

```yaml
schema_version: 1

context:
...
  python_min: 3.7

...

requirements:
  host:
    - python 3.7.*
```

instead of 

```yaml
schema_version: 1

context:
...
  python_min: 3.7

...

requirements:
  host:
    - python ${{ python_min }}.*
  
```

**Comment by matthewfeickert** [comment]
*The second YAML snippet here should be

```yaml
  run:
    - python >=${{ python_min }}

...

  - requirements:
      run:
        - python ${{ python_min }}.*
```

e.g. this is what I _expected_ to happen.

**Comment by schuylermartin45** [comment]
As a heads-up, I am incredibly resource constrained right now. There are some internal projects I have to tend to that are preventing me from handling CRM bugs in a timely fashion. But I do appreciate these bug reports!

Relates to #308 and #309

**Comment by schuylermartin45** [comment]
So I'm seeing something slightly different on the recipe provided. I'm seeing in most cases that `{{ python_min }}` is being converted to `${{ python_min }}` correctly.

What I think is causing this issue is the logic that attempts to handle "ambiguous dependency versions" (see https://github.com/conda-incubator/conda-recipe-manager/issues/276) is rendering-out the variable instead of preserving it.

So anytime the converter encounters `{{ python_min }}.*` (or presumably any other `{{ <var> }}.*`, the variable gets rendered to form `3.7.*` instead of being left alone.

**Comment by matthewfeickert** [comment]
> So I'm seeing something slightly different on the recipe provided. I'm seeing in most cases that `{{ python_min }}` is being converted to `${{ python_min }}` correctly.

No, that's from me manually editing it. c.f. the original issue (https://github.com/hadim/feedrattler/issues/4) where I point to the actual commits before editing with errors: https://github.com/conda-forge/pyhf-feedstock/commit/87386f9a3a7ff1fbbc52f4229804609ec460b3e0

**Comment by schuylermartin45** [comment]
Cool, I think that further confirms my theory then.

To do this "properly" I think is going to take a little bit of effort. I'd like to rework some of the dependency management to be more "variable aware" than the current representation allows.

**Comment by beckermr** [comment]
I am now seeing that crm replaces `{{ python_min }}` with the value appended with `.*`.

See this output for an example:


```
[WARNING]: Version on dependency changed to: python 3.10.*
[WARNING]: Field at `/about/license_family` is no longer supported.
[WARNING]: Field at `/about/doc_source_url` is no longer supported.
0 errors and 3 warnings were found.
```

generated recipe.yaml:

```
schema_version: 1

context:
  name: nbclient
  version: "0.11.0"
  python_min: "3.10"
  build: 0

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 04a134a5b087f2c5887f228aca155db50169b8cd9334dee6942c8e927e56081a

build:
  number: ${{ build }}
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python 3.10.*
    - pip
    - hatchling
  run:
    - python >=${{ python_min }}
    - jupyter_client >=7.0.0
    - jupyter_core >=5.4
    - nbformat >=5.2.0
    - traitlets >=5.13

tests:
  - python:
      imports:
        - nbclient
      pip_check: true
      python_version: ${{ python_min }}

about:
  license: BSD-3-Clause
  license_file: LICENSE
  summary: A client library for executing notebooks. Formally nbconvert's ExecutePreprocessor.
  description: |
    NBClient is a tool for parameterizing and executing Jupyter Notebooks.
    NBClient lets you execute notebooks. Similar in nature to jupyter_client, as the jupyter_client
    is to the jupyter protocol nbclient is to notebooks allowing for execution contexts to be run.
  homepage: https://jupyter.org
  repository: https://github.com/jupyter/nbclient
  documentation: https://nbclient.readthedocs.io

extra:
  recipe-maintainers:
    - davidbrochart
```

original meta.yaml:

```
{% set name = "nbclient" %}
{% set version = "0.11.0" %}
{% set python_min = "3.10" %}
{% set build = 0 %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 04a134a5b087f2c5887f228aca155db50169b8cd9334dee6942c8e927e56081a

build:
  number: {{ build }}
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - jupyter_client >=7.0.0
    - jupyter_core >=5.4
    - nbformat >=5.2.0
    - traitlets >=5.13

test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - nbclient
  commands:
    - pip check

about:
  home: https://jupyter.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A client library for executing notebooks. Formally nbconvert's ExecutePreprocessor.
  description: |
    NBClient is a tool for parameterizing and executing Jupyter Notebooks.
    NBClient lets you execute notebooks. Similar in nature to jupyter_client, as the jupyter_client
    is to the jupyter protocol nbclient is to notebooks allowing for execution contexts to be run.
  dev_url: https://github.com/jupyter/nbclient
  doc_url: https://nbclient.readthedocs.io
  doc_source_url: https://github.com/jupyter/nbclient/tree/master/docs

extra:
  recipe-maintainers:
    - davidbrochart
```
