### ISSUE TITLE
`pip_check` should be explcitly added

### ISSUE THREAD

**Issue by mikemhenry** [conda/conda-recipe-manager#312]
**What happened?**

Because `pip check`runs by default in `rattler-build`, `pip_check` should be set to `true` or `false` depending on if the original recipe had a `pip check` command. As it stands now, converting a (python) recipe will now always run `pip check`.

**To Reproduce**

**Additional Details (please complete the following information):**
 - OS: [e.g. MacOS M1, Windows]
 - Conda Recipe Manager version [e.g. `0.2.0`]
 - Any other context about the problem that was found.

**Comment by schuylermartin45** [comment]
Can you provide an example or additional details to reproduce this? I'm [almost certain](https://github.com/conda-incubator/conda-recipe-manager/blob/main/conda_recipe_manager/parser/recipe_parser_convert.py#L639) we have logic that does look for if pip check exists (and that it the target is for a "python recipe").

I will also note that I can not currently make guarantees on a timeline for a fix as I have my hands tied up in some other projects right now.

**Comment by mikemhenry** [comment]
@schuylermartin45 thank you for all of your hard work 🙏 

This is the feedstock where I ran into this "bug"
https://github.com/conda-forge/konnektor-feedstock/pull/6

Good to see this check exists in the source, maybe this is an edge case then?

**Comment by mikemhenry** [comment]
The original recipe had this in the test block:
```
test:
  imports:
    - konnektor
  commands:
    - pytest --pyargs konnektor
  requires:
    - pytest
    - python {{ python_min }}
```
and the conversion added:
```
tests:
  - python:
      imports:
        - konnektor
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pytest
        - python ${{ python_min }}.*
    script:
      - pytest --pyargs konnektor
```
I should note I used https://github.com/hadim/feedrattler and not this package directly
