### ISSUE TITLE
build.force_use_keys is now build.variant.use_keys in convert

### ISSUE THREAD

**Issue by minrk** [conda/conda-recipe-manager#338]
Should be a straightforward relocation, like #298

In v0:

```yaml
build:
  force_use_keys:
    - a
    - b
```

should become:

```yaml
build:
  variant:
    use_keys:
      - a
      - b
```
